### ISSUE TITLE
Site Structure

### ISSUE THREAD

**Issue by victorb** [ipld/website#14]
Things missing from the website:
- [x] Landing Page
  - [ ] Small visual demo < Most important for an understanding
    - [ ] To figure out (issue here: https://github.com/ipld/website/issues/12)
  - [X] Features - see https://github.com/ipld/website/issues/15
  - [X] Languages currently supported (go, js, others coming soon) - see https://github.com/ipld/website/issues/16
  - [X] Talks & Conferences - see https://github.com/ipld/website/issues/17
  - [X] Contribute & Community - see https://github.com/ipld/website/issues/19
- [x] Install / Examples < Should be clearly linked from landing page in CTA - see https://github.com/ipld/website/issues/21
  - [ ] Requirements / Installation (go/js)
  - [x] <fill_me_out> Pending: https://github.com/ipld/website/issues/13
  - [ ] Links to more examples

Link to specification + Github repository on every page in header

**Comment by victorb** [comment]
Closing this in favor of the other issues created and linked in this issue.
